## HW - Day048

link: https://www.kaggle.com/c/data-science-london-scikit-learn/data

In [8]:
import pandas as pd
from sklearn import datasets, metrics
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split

C:\Users\KenChen\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [1]:
train = pd.read_csv("data/data-science-london-scikit-learn/train.csv", header = None)
train_y = pd.read_csv("data/data-science-london-scikit-learn/trainLabels.csv", header = None)
test = pd.read_csv("data/data-science-london-scikit-learn/test.csv", header = None)

NameError: name 'pd' is not defined

In [58]:
X_train, X_test, Y_train, Y_test = train_test_split(train, train_y, test_size=0.3, random_state=2)

GBR = GradientBoostingRegressor()

GBR.fit(X_train, Y_train)

y_pred = GBR.predict(X_test)

C:\Users\KenChen\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [67]:
from sklearn.metrics import r2_score
score = r2_score(Y_test, y_pred)
print("Score: ", score)

Score:  0.5893726289710992

In [68]:
y_predictions = GBR.predict(test)

In [69]:
# import numpy as np
# np.savetxt('data/data-science-london-scikit-learn/HW_048_Result.csv', y_predictions, delimiter=",")

In [70]:
submit = pd.DataFrame(columns=["Id","Solution"])

In [76]:
submit['Id'] = np.arange(1,submit.shape[0]+1)
submit['Solution'] = y_predictions

In [78]:
submit['Solution'] = submit['Solution'].round().astype(int)

In [80]:
submit.to_csv('data/data-science-london-scikit-learn/HW_048_Result.csv',index = False)

In [79]:

submit

        Id  Solution
0        1         1
1        2         0
2        3         0
3        4         0
4        5         0
5        6         1
6        7         0
7        8         1
8        9         0
9       10         0
10      11         1
11      12         1
12      13         1
13      14         0
14      15         0
15      16         1
16      17         0
17      18         1
18      19         1
19      20         1
20      21         1
21      22         1
22      23         0
23      24         0
24      25         1
25      26         1
26      27         1
27      28         0
28      29         1
29      30         0
...    ...       ...
8970  8971         0
8971  8972         0
8972  8973         1
8973  8974         0
8974  8975         0
8975  8976         1
8976  8977         0
8977  8978         1
8978  8979         1
8979  8980         1
8980  8981         1
8981  8982         1
8982  8983         1
8983  8984         0
8984  8985         0
8985  8986         1
8986  8987         0
8987  8988         0
8988  8989         1
8989  8990         0
8990  8991         0
8991  8992         1
8992  8993         0
8993  8994         1
8994  8995         1
8995  8996         0
8996  8997         1
8997  8998         1
8998  8999         0
8999  9000         1

[9000 rows x 2 columns]